name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 23f1002770@ds.study.iitm.ac.in
        run: echo "Hello, world!"
      - name: Another step
        run: echo "This is a test action."
